cc_library(
    name = "MergeSortedArray",
    hdrs = ["MergeSortedArray.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "MergeSortedArrayTest",
    srcs = ["MergeSortedArrayTest.cpp"],
    deps = [
        ":MergeSortedArray",
        "@googletest//:gtest_main",
    ],
)
